### ISSUE TITLE
SMEO-11 tidak bisa add TB ketika Hasil foto toraks bernilai SELAIN `Tidak Dilakukan`

### ISSUE THREAD

**Issue by ardihikaru** [bgsi-registry/OpenEHR-registry-template#31]
Secara OPT, seharusnya field `Pemeriksaan yang tidak dikerjakan` bersifat `OPSIONAL`, bukan `mandatory`
![Image](https://user-images.githubusercontent.com/9791562/204108010-7750b409-5871-4231-b553-ff7675c1ecd8.png)

Kondisi sekarang, jika `Hasil foto toraks` dipilih value `Negative` atau `Positive`, maka akan terdapat error dikarenakan logic di OPT:
```
2022-11-26 20:10:46.876  WARN [traceId=c3a659ad-a0f0-4c58-afa6-4bd6648f9b81] 9 --- [nio-8080-exec-8] o.e.r.ehrscape.EhrScapeExceptionHandler  : /content[openEHR-EHR-SECTION.adhoc.v1, 1]/items[openEHR-EHR-ACTION.service.v0, 4]/description: Attribute description of class ACTION does not match existence 1..1
```

dimana `openEHR-EHR-ACTION.service.v0, 4]/description` yang dimaksud disini adalah field untuk `Pemeriksaan yang tidak dikerjakan` yang bersifat `lower bound = 1`

Output:
- Informasi berikut `WAJIB BERSIFAT OPSIONAL dari OPT`
```
        "tuberculosis-adm.v4/admisi/service/pemeriksaan_yang_tidak_dikerjakan|code": "SCTID::399208008",
        "tuberculosis-adm.v4/admisi/service/pemeriksaan_yang_tidak_dikerjakan|value": "Foto toraks",
        "tuberculosis-adm.v4/admisi/service/pemeriksaan_yang_tidak_dikerjakan|terminology": "SNOMED-CT",
```

TODO:
- [ ] Form `Admisi` > `Hasil Foto Toraks` bagian `alasan dikerjakan`, butuh untuk di set sebagai `OPSIONAL`
- [ ] Form `Lab` > `Hasil pemeriksaan mikroskopis` * blm optional, butuh untuk di set sebagai `OPSIONAL`

**Comment by lamurian** [comment]
Double-checked in the Archetype Designer and repository, this field is non-mandatory with a cardinality of `1..1`

Check out: https://github.com/bgsi-registry/OpenEHR-registry-template/blob/master/hubs/infectious-disease/v4.2.0/tuberculosis-adm.v4.json#L879-L920
![](https://i.ibb.co/VDQQZL9/2022-11-27-120639-800x269-scrot.png)
![](https://i.ibb.co/cD4BWqg/2022-11-27-120655-710x266-scrot.png)
